# Generated by Django 3.0.8 on 2020-07-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
    ]
