# Generated by Django 3.0.8 on 2020-07-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0002_auto_20200728_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMapping',
            fields=[
                ('role_mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_app.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts_app.User')),
            ],
        ),
    ]
