# Generated by Django 3.0.8 on 2020-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0004_remove_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
