# Generated by Django 3.0.8 on 2020-07-28 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts_app', '0005_auto_20200728_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_date',
            field=models.DateTimeField(),
        ),
    ]
